### ISSUE TITLE
No SSL module - pip fails

### ISSUE THREAD

**Issue by gjedeer** [nmusatti/source-python#2]
By default, when I ran this playbook on CentOS 7, it worked nicely but resulted in an installation with broken `pip`. The reason was, `openssl-devel` has not been installed in the system, so `./configure` has built Python without OpenSSL, and pip failed.

After `yum install openssl-devel`, I had a working installation with pip.

I suggest adding this package and its Debian counterpart to the "Install dependencies" step.

**Comment by nmusatti** [comment]
I'm puzzled because it's already there, as you can see here: https://github.com/nmusatti/source-python/blob/master/tasks/main.yml
Which python release were you trying to install? 3.11 for instance requires a newer OpenSSL version than the one provided by CentOS 7.

**Comment by gjedeer** [comment]
Okay, I have no idea how I came across this problem. I see that you're installing openssl-devel on the playbook. Wanted to reproduce the problem in a fresh CentOS 7 container and the problem did not exist. Thank you fro your quick reply.
